name: Deploy Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Playbook
        env:
          ANSIBLE_HOST_CHECKING: 'False' 
        run: |
          ansible-playbook -i inventory.ini playbook.yml
